# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/hd63433/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/hd283869/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/hd285507/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k277/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k2100/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k2101/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k2102/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k2136/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k2284/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/toi1807/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/toi2048/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/toi2076/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/v1298tau/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/v2689ori/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k2104/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/otser/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k2264/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k2103/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k295/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/k225/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/ep211901114/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/evlac/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/adleo/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/bd+5_378/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/iras04125/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/kepler1627/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/kepler970/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/koi7913/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
# python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/raw_hpf_data/compiled_fits_files/koi3876/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer
python run_hpf_tellurics.py ~/research/HPF_Work/HPF_Data/a_star_data/fits_files/ --grid_name hpf_lblrtm-aer_20250123_v001 --output_dir telluric_output_aer